<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>bigdata_l6-github – Social Data Analysis and Visualization</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-956b8a4ec41f03f761f91fad8c3a3e27.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-c2a6d3abc2894eadef3e844b666af903.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-956b8a4ec41f03f761f91fad8c3a3e27.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Social Data Analysis and Visualization</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../schedule.html"> 
<span class="menu-text">Masters Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../schedule_phd.html"> 
<span class="menu-text">PhD Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../install.html"> 
<span class="menu-text">Install R</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/aysedeniz09/IntroCSS"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Getting Started</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Social Data Analysis and Visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Schedule - Masters</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../schedule_phd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Schedule - PhD</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../install.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to Install R Studio</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Class Sessions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/01/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 1 - Why Computational Social Science?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/02/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 2 - Data Collection and Wrangling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/03/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 3 - GGPlot and Visualizations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/04/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 4 - Computational Research</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/05/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 5 - Descriptive Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/06/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 6 - Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/07/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 7 - Dictionary Methods &amp; Word Embeddings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/08/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 8 - Midterm Exam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/09/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 9 - Topic Modeling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/10/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 10 - Unsupervised Machine Learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/11/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 11 - Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/12/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 12 - Online Social Movements</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sessions/13/session.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Session 13 - From Data to Conclusions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Resources</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../resources/cheatsheets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Cheatsheets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../resources/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datasets</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#statistics" id="toc-statistics" class="nav-link active" data-scroll-target="#statistics">Statistics</a>
  <ul class="collapse">
  <li><a href="#lecture-6-table-of-contents" id="toc-lecture-6-table-of-contents" class="nav-link" data-scroll-target="#lecture-6-table-of-contents">Lecture 6 Table of Contents</a></li>
  <li><a href="#setup-create-example-dataset" id="toc-setup-create-example-dataset" class="nav-link" data-scroll-target="#setup-create-example-dataset">Setup: Create Example Dataset</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">1. Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#what-is-hypothesis-testing" id="toc-what-is-hypothesis-testing" class="nav-link" data-scroll-target="#what-is-hypothesis-testing">1.1 What is Hypothesis Testing?</a></li>
  <li><a href="#t-test-comparing-two-groups" id="toc-t-test-comparing-two-groups" class="nav-link" data-scroll-target="#t-test-comparing-two-groups">1.2 T-Test: Comparing Two Groups</a></li>
  <li><a href="#visualizing-t-tests" id="toc-visualizing-t-tests" class="nav-link" data-scroll-target="#visualizing-t-tests">1.3 Visualizing T-Tests</a></li>
  <li><a href="#anova-comparing-multiple-groups" id="toc-anova-comparing-multiple-groups" class="nav-link" data-scroll-target="#anova-comparing-multiple-groups">1.4 ANOVA: Comparing Multiple Groups</a></li>
  <li><a href="#visualizing-anova" id="toc-visualizing-anova" class="nav-link" data-scroll-target="#visualizing-anova">1.5 Visualizing ANOVA</a></li>
  </ul></li>
  <li><a href="#regression-models" id="toc-regression-models" class="nav-link" data-scroll-target="#regression-models">2. Regression Models</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">2.1 Simple Linear Regression</a></li>
  <li><a href="#interpreting-regression-output" id="toc-interpreting-regression-output" class="nav-link" data-scroll-target="#interpreting-regression-output">2.2 Interpreting Regression Output</a></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">2.3 Multiple Linear Regression</a></li>
  <li><a href="#dummy-variables" id="toc-dummy-variables" class="nav-link" data-scroll-target="#dummy-variables">2.4 Dummy Variables</a></li>
  </ul></li>
  <li><a href="#visualizing-regression" id="toc-visualizing-regression" class="nav-link" data-scroll-target="#visualizing-regression">3. Visualizing Regression</a>
  <ul class="collapse">
  <li><a href="#scatter-plots-with-regression-lines" id="toc-scatter-plots-with-regression-lines" class="nav-link" data-scroll-target="#scatter-plots-with-regression-lines">3.1 Scatter Plots with Regression Lines</a></li>
  <li><a href="#coefficient-plots" id="toc-coefficient-plots" class="nav-link" data-scroll-target="#coefficient-plots">3.2 Coefficient Plots</a></li>
  <li><a href="#marginal-effects-plots" id="toc-marginal-effects-plots" class="nav-link" data-scroll-target="#marginal-effects-plots">3.3 Marginal Effects Plots</a></li>
  </ul></li>
  <li><a href="#generalized-linear-models-glms" id="toc-generalized-linear-models-glms" class="nav-link" data-scroll-target="#generalized-linear-models-glms">4. Generalized Linear Models (GLMs)</a>
  <ul class="collapse">
  <li><a href="#when-to-use-glms" id="toc-when-to-use-glms" class="nav-link" data-scroll-target="#when-to-use-glms">4.1 When to Use GLMs</a></li>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link" data-scroll-target="#poisson-regression">4.2 Poisson Regression</a></li>
  </ul></li>
  <li><a href="#interaction-terms" id="toc-interaction-terms" class="nav-link" data-scroll-target="#interaction-terms">5. Interaction Terms</a>
  <ul class="collapse">
  <li><a href="#what-are-interactions" id="toc-what-are-interactions" class="nav-link" data-scroll-target="#what-are-interactions">5.1 What are Interactions?</a></li>
  <li><a href="#visualizing-interactions" id="toc-visualizing-interactions" class="nav-link" data-scroll-target="#visualizing-interactions">5.2 Visualizing Interactions</a></li>
  </ul></li>
  <li><a href="#model-diagnostics" id="toc-model-diagnostics" class="nav-link" data-scroll-target="#model-diagnostics">6. Model Diagnostics</a>
  <ul class="collapse">
  <li><a href="#assumptions-of-linear-regression" id="toc-assumptions-of-linear-regression" class="nav-link" data-scroll-target="#assumptions-of-linear-regression">6.1 Assumptions of Linear Regression</a></li>
  <li><a href="#checking-assumptions" id="toc-checking-assumptions" class="nav-link" data-scroll-target="#checking-assumptions">6.2 Checking Assumptions</a></li>
  <li><a href="#the-performance-package" id="toc-the-performance-package" class="nav-link" data-scroll-target="#the-performance-package">6.3 The performance Package</a></li>
  </ul></li>
  <li><a href="#class-exercise" id="toc-class-exercise" class="nav-link" data-scroll-target="#class-exercise">Class Exercise</a></li>
  <li><a href="#lecture-6-cheat-sheet" id="toc-lecture-6-cheat-sheet" class="nav-link" data-scroll-target="#lecture-6-cheat-sheet">Lecture 6 Cheat Sheet</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>





<section id="statistics" class="level1">
<h1>Statistics</h1>
<p>Dr.&nbsp;Ayse D. Lokmanoglu Lecture 6, (B) Feb 25, (A) Mar 2</p>
<section id="lecture-6-table-of-contents" class="level2">
<h2 class="anchored" data-anchor-id="lecture-6-table-of-contents">Lecture 6 Table of Contents</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Section</th>
<th>Topic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Hypothesis Testing</td>
</tr>
<tr class="even">
<td>1.1</td>
<td>What is Hypothesis Testing?</td>
</tr>
<tr class="odd">
<td>1.2</td>
<td>T-Test: Comparing Two Groups</td>
</tr>
<tr class="even">
<td>1.3</td>
<td>Visualizing T-Tests</td>
</tr>
<tr class="odd">
<td>1.4</td>
<td>ANOVA: Comparing Multiple Groups</td>
</tr>
<tr class="even">
<td>1.5</td>
<td>Visualizing ANOVA</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Regression Models</td>
</tr>
<tr class="even">
<td>2.1</td>
<td>Simple Linear Regression</td>
</tr>
<tr class="odd">
<td>2.2</td>
<td>Interpreting Regression Output</td>
</tr>
<tr class="even">
<td>2.3</td>
<td>Multiple Linear Regression</td>
</tr>
<tr class="odd">
<td>2.4</td>
<td>Dummy Variables</td>
</tr>
<tr class="even">
<td>3</td>
<td>Visualizing Regression</td>
</tr>
<tr class="odd">
<td>3.1</td>
<td>Scatter Plots with Regression Lines</td>
</tr>
<tr class="even">
<td>3.2</td>
<td>Coefficient Plots</td>
</tr>
<tr class="odd">
<td>3.3</td>
<td>Marginal Effects Plots</td>
</tr>
<tr class="even">
<td>4</td>
<td>Generalized Linear Models</td>
</tr>
<tr class="odd">
<td>4.1</td>
<td>When to Use GLMs</td>
</tr>
<tr class="even">
<td>4.2</td>
<td>Poisson Regression</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Interaction Terms</td>
</tr>
<tr class="even">
<td>5.1</td>
<td>What are Interactions?</td>
</tr>
<tr class="odd">
<td>5.2</td>
<td>Visualizing Interactions</td>
</tr>
<tr class="even">
<td>6</td>
<td>Model Diagnostics</td>
</tr>
<tr class="odd">
<td>6.1</td>
<td>Assumptions of Linear Regression</td>
</tr>
<tr class="even">
<td>6.2</td>
<td>Checking Assumptions</td>
</tr>
<tr class="odd">
<td>6.3</td>
<td>The performance Package</td>
</tr>
</tbody>
</table>
<hr>
<p><strong>ALWAYS</strong> load our libraries first</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
<section id="setup-create-example-dataset" class="level2">
<h2 class="anchored" data-anchor-id="setup-create-example-dataset">Setup: Create Example Dataset</h2>
<p>We’ll use the same student dataset throughout this lecture:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>student_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/aysedeniz09/IntroCSS/refs/heads/main/data/student_lifestyle_dataset.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(student_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## # A tibble: 6 × 12
##   Student_ID Study_Hours_Per_Day Extracurricular_Hours_Per…¹ Sleep_Hours_Per_Day
##        &lt;dbl&gt;               &lt;dbl&gt;                       &lt;dbl&gt;               &lt;dbl&gt;
## 1          1                 6.9                         3.8                 8.7
## 2          2                 5.3                         3.5                 8  
## 3          3                 5.1                         3.9                 9.2
## 4          4                 6.5                         2.1                 7.2
## 5          5                 8.1                         0.6                 6.5
## 6          6                 6                           2.1                 8  
## # ℹ abbreviated name: ¹​Extracurricular_Hours_Per_Day
## # ℹ 8 more variables: Social_Hours_Per_Day &lt;dbl&gt;,
## #   Physical_Activity_Hours_Per_Day &lt;dbl&gt;, GPA &lt;dbl&gt;, Stress_Level &lt;chr&gt;,
## #   college &lt;chr&gt;, GPA_Level &lt;chr&gt;, Stress_Level2 &lt;chr&gt;, books_read &lt;dbl&gt;</code></pre>
<hr>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">1. Hypothesis Testing</h2>
<section id="what-is-hypothesis-testing" class="level3">
<h3 class="anchored" data-anchor-id="what-is-hypothesis-testing">1.1 What is Hypothesis Testing?</h3>
<p>Hypothesis testing allows you to make <strong>inferences about populations</strong> based on sample data. It answers: “Is the pattern I see in my data real, or could it be due to chance?”</p>
<p><strong>Key Components:</strong></p>
<ul>
<li><strong>Null Hypothesis (H₀)</strong>: No effect or difference exists</li>
<li><strong>Alternative Hypothesis (H₁)</strong>: An effect or difference exists</li>
<li><strong>p-value</strong>: Probability of observing your data if H₀ is true</li>
<li><strong>Significance level (α)</strong>: Threshold for rejecting H₀ (usually 0.05)</li>
</ul>
<p><strong>Decision Rule:</strong></p>
<ul>
<li>If p &lt; α: <strong>Reject H₀</strong> (result is statistically significant)</li>
<li>If p ≥ α: <strong>Fail to reject H₀</strong> (result is not statistically significant)</li>
</ul>
<p><mark><strong>Important:</strong> “Fail to reject” ≠ “Accept H₀”. We never prove the null hypothesis is true!</mark></p>
<hr>
</section>
<section id="t-test-comparing-two-groups" class="level3">
<h3 class="anchored" data-anchor-id="t-test-comparing-two-groups">1.2 T-Test: Comparing Two Groups</h3>
<p>A <strong>t-test</strong> compares the means of two groups to determine if they are significantly different.</p>
<p><strong>Types of T-Tests:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 40%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th>Use Case</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Independent</td>
<td>Two unrelated groups</td>
<td>Males vs.&nbsp;Females</td>
</tr>
<tr class="even">
<td>Paired</td>
<td>Same subjects, two conditions</td>
<td>Before vs.&nbsp;After treatment</td>
</tr>
<tr class="odd">
<td>One-sample</td>
<td>Sample vs.&nbsp;known value</td>
<td>Sample mean vs.&nbsp;population mean</td>
</tr>
</tbody>
</table>
<p><strong>Example:</strong> Do male and female CS students study different hours?</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for CS students</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>AS_students <span class="ot">&lt;-</span> student_data <span class="sc">|&gt;</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(college <span class="sc">==</span> <span class="st">"Arts &amp; Sciences"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Independent t-test</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(Study_Hours_Per_Day <span class="sc">~</span> Stress_Level2, <span class="at">data =</span> AS_students)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>t_test_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Study_Hours_Per_Day by Stress_Level2
## t = 15.245, df = 310.19, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means between group High and group LowModerate is not equal to 0
## 95 percent confidence interval:
##  1.526264 1.978624
## sample estimates:
##        mean in group High mean in group LowModerate 
##                  8.362941                  6.610497</code></pre>
<p><strong>Interpreting the Output:</strong></p>
<ul>
<li><strong>t-statistic</strong> (t = 15.245): How many standard errors the difference is from 0</li>
<li><strong>df</strong> (df = 310.19): Degrees of freedom (affects the t-distribution)</li>
<li><strong>p-value</strong> (p &lt; 2.2e-16): Probability of seeing this difference by chance</li>
<li><strong>95% CI</strong> ([1.53, 1.98]): Range likely containing the true difference in means</li>
<li><strong>Group means</strong>: High Stress = 8.36 hours, Low/Moderate Stress = 6.61 hours</li>
</ul>
<p><strong>Conclusion:</strong> p &lt; 0.001, so we reject H₀. There is a significant difference in study hours between stress levels. Students with high stress study approximately 1.75 more hours per day than students with low/moderate stress.</p>
<p><strong>How to report:</strong> <em>A Welch two-sample t-test revealed a significant difference in daily study hours between high stress (M = 8.36) and low/moderate stress (M = 6.61) students, t(310.19) = 15.25, p &lt; .001, 95% CI [1.53, 1.98].</em></p>
<hr>
</section>
<section id="visualizing-t-tests" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-t-tests">1.3 Visualizing T-Tests</h3>
<p><strong>Boxplot with means:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(AS_students, <span class="fu">aes</span>(<span class="at">x =</span> Stress_Level2, <span class="at">y =</span> Study_Hours_Per_Day, <span class="at">fill =</span> Stress_Level2)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Study Hours by Stress Level (Arts &amp; Sciences Students)"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"t-test p-value ="</span>, <span class="fu">round</span>(t_test_result<span class="sc">$</span>p.value, <span class="dv">3</span>)),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Stress Level"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Study Hours"</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>) <span class="sc">+</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-4-1.png" class="img-fluid"><!-- --></p>
<p><strong>Violin plot:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(AS_students, <span class="fu">aes</span>(<span class="at">x =</span> Stress_Level2, <span class="at">y =</span> Study_Hours_Per_Day, <span class="at">fill =</span> Stress_Level2)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">trim =</span> <span class="cn">FALSE</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of Study Hours by Stress Level"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Stress Level"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Study Hours"</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>) <span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-5-1.png" class="img-fluid"><!-- --></p>
<p><strong>Bar plot with error bars:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate summary statistics</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>stress_summary <span class="ot">&lt;-</span> AS_students <span class="sc">|&gt;</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Stress_Level2) <span class="sc">|&gt;</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(Study_Hours_Per_Day),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="fu">sd</span>(Study_Hours_Per_Day) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">n</span>()),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(stress_summary, <span class="fu">aes</span>(<span class="at">x =</span> Stress_Level2, <span class="at">y =</span> mean, <span class="at">fill =</span> Stress_Level2)) <span class="sc">+</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>se, <span class="at">ymax =</span> mean <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>se), </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(mean, <span class="dv">1</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Mean Study Hours by Stress Level (±95% CI)"</span>,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Stress Level"</span>,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean Study Hours"</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>) <span class="sc">+</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-6-1.png" class="img-fluid"><!-- --></p>
<hr>
</section>
<section id="anova-comparing-multiple-groups" class="level3">
<h3 class="anchored" data-anchor-id="anova-comparing-multiple-groups">1.4 ANOVA: Comparing Multiple Groups</h3>
<p><strong>ANOVA</strong> (Analysis of Variance) extends the t-test to compare means across <strong>three or more groups</strong>.</p>
<ul>
<li><strong>H₀</strong>: All group means are equal (μ₁ = μ₂ = μ₃)</li>
<li><strong>H₁</strong>: At least one group mean is different</li>
</ul>
<p><strong>Example:</strong> Do students from different majors study different hours?</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-way ANOVA</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(Study_Hours_Per_Day <span class="sc">~</span> college, <span class="at">data =</span> student_data)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>##               Df Sum Sq Mean Sq F value Pr(&gt;F)
## college        4      3  0.6442   0.317  0.867
## Residuals   1995   4050  2.0302</code></pre>
<p><strong>Interpreting the Output:</strong></p>
<ul>
<li><strong>F value</strong> (0.317): Ratio of between-group variance to within-group variance</li>
<li><strong>Pr(&gt;F)</strong> (0.867): p-value for the F-test</li>
</ul>
<p><strong>Conclusion:</strong> p = 0.867 &gt; 0.05, so we fail to reject H₀. There is no significant difference in GPA across colleges.</p>
<p><strong>Post-hoc test:</strong> Which majors are different from each other?</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tukey's HSD (Honestly Significant Difference)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(anova_result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Study_Hours_Per_Day ~ college, data = student_data)
## 
## $college
##                                      diff        lwr       upr     p adj
## Communication-Arts &amp; Sciences  0.09074074 -0.2209765 0.4024580 0.9321845
## Education-Arts &amp; Sciences     -0.01271548 -0.2919796 0.2665486 0.9999462
## Humanities-Arts &amp; Sciences    -0.00905683 -0.2806320 0.2625183 0.9999845
## Medicine-Arts &amp; Sciences       0.04006047 -0.2382109 0.3183318 0.9949622
## Education-Communication       -0.10345622 -0.4016537 0.1947413 0.8783008
## Humanities-Communication      -0.09979757 -0.3908068 0.1912116 0.8827707
## Medicine-Communication        -0.05068027 -0.3479482 0.2465877 0.9903715
## Humanities-Education           0.00365865 -0.2522850 0.2596023 0.9999995
## Medicine-Education             0.05277595 -0.2102621 0.3158140 0.9822233
## Medicine-Humanities            0.04911730 -0.2057428 0.3039774 0.9847059</code></pre>
<p><strong>How to report:</strong> <em>A one-way ANOVA revealed no significant differences in daily study hours among colleges, F(4, 1995) = 0.32, p = .867. Post-hoc Tukey tests confirmed no significant pairwise differences between any colleges (all p &gt; .05).</em></p>
<hr>
</section>
<section id="visualizing-anova" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-anova">1.5 Visualizing ANOVA</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(student_data, <span class="fu">aes</span>(<span class="at">x =</span> college, <span class="at">y =</span> Study_Hours_Per_Day, <span class="at">fill =</span> college)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Study Hours by College"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"ANOVA F(4, 1995) ="</span>, <span class="fu">round</span>(<span class="fu">summary</span>(anova_result)[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">`</span><span class="at">F value</span><span class="st">`</span>[<span class="dv">1</span>], <span class="dv">2</span>), </span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                     <span class="st">", p = 0.867"</span>),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"College"</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Study Hours"</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>) <span class="sc">+</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-9-1.png" class="img-fluid"><!-- --></p>
<p><strong>Comparison Table:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Test</th>
<th>Groups</th>
<th>Compares</th>
<th>Statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T-test</td>
<td>2</td>
<td>Means</td>
<td>t-statistic</td>
</tr>
<tr class="even">
<td>ANOVA</td>
<td>3+</td>
<td>Means</td>
<td>F-statistic</td>
</tr>
</tbody>
</table>
<hr>
<section id="class-exercise-hypothesis-testing" class="level4">
<h4 class="anchored" data-anchor-id="class-exercise-hypothesis-testing">Class Exercise: Hypothesis Testing</h4>
<ol type="1">
<li>Perform a t-test comparing GPA for all stress levels (all colleges).</li>
<li>Perform an ANOVA comparing GPA across colleges</li>
<li>If ANOVA is significant, run Tukey’s HSD to identify which colleges differ.</li>
<li>Visualize your results with appropriate plots.</li>
</ol>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Your workspace</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
</section>
</section>
<section id="regression-models" class="level2">
<h2 class="anchored" data-anchor-id="regression-models">2. Regression Models</h2>
<p>Regression models examine the <strong>relationship between variables</strong> and allow us to <strong>predict outcomes</strong>.</p>
<section id="simple-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="simple-linear-regression">2.1 Simple Linear Regression</h3>
<p>A simple linear regression models the relationship between <strong>one predictor</strong> (X) and <strong>one outcome</strong> (Y):</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X + \epsilon\]</span></p>
<p>Where: - <span class="math inline">\(\beta_0\)</span> = Intercept (predicted Y when X = 0) - <span class="math inline">\(\beta_1\)</span> = Slope (change in Y for one-unit increase in X) - <span class="math inline">\(\epsilon\)</span> = Error term</p>
<p><strong>Example:</strong> Does study time predict exam scores?</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit simple linear regression</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>simple_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(GPA <span class="sc">~</span> Study_Hours_Per_Day, <span class="at">data =</span> student_data)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simple_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## 
## Call:
## lm(formula = GPA ~ Study_Hours_Per_Day, data = student_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.60834 -0.13516 -0.00103  0.13606  0.79925 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         1.964228   0.024236   81.05   &lt;2e-16 ***
## Study_Hours_Per_Day 0.154061   0.003185   48.38   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.2027 on 1998 degrees of freedom
## Multiple R-squared:  0.5394, Adjusted R-squared:  0.5392 
## F-statistic:  2340 on 1 and 1998 DF,  p-value: &lt; 2.2e-16</code></pre>
<hr>
</section>
<section id="interpreting-regression-output" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-regression-output">2.2 Interpreting Regression Output</h3>
<p><strong>Coefficients:</strong></p>
<ul>
<li><strong>Intercept</strong> (1.96): Predicted GPA when Study_Hours_Per_Day = 0</li>
<li><strong>Study_Hours_Per_Day</strong> (0.15): For each additional hour studied, GPA increases by 0.15 points</li>
</ul>
<p><strong>Model Fit:</strong></p>
<ul>
<li><strong>R²</strong> (0.54): 54% of variance in GPA is explained by study hours</li>
<li><strong>Adjusted</strong> R² (0.54): R² adjusted for number of predictors</li>
<li><strong>F-statistic</strong> (2340): Overall model significance (p &lt; .001)</li>
</ul>
<p><strong>Statistical Significance:</strong></p>
<ul>
<li>Both coefficients have p &lt; 0.001 (***), indicating they are significantly different from 0</li>
</ul>
<p><strong>The Regression Equation:</strong></p>
<p><span class="math display">\[\text{GPA} = 1.96 + 0.15 \times \text{Study Hours Per Day}\]</span></p>
<p><strong>Prediction Example:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict score for someone who studies 8 hours per day</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>predicted_gpa <span class="ot">&lt;-</span> <span class="fl">1.96</span> <span class="sc">+</span> <span class="fl">0.15</span> <span class="sc">*</span> <span class="dv">8</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Predicted GPA for 8 study hours:"</span>, predicted_gpa)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## Predicted GPA for 8 study hours: 3.16</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Or use predict()</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(simple_model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Study_Hours_Per_Day =</span> <span class="dv">8</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>##        1 
## 3.196719</code></pre>
<hr>
</section>
<section id="multiple-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="multiple-linear-regression">2.3 Multiple Linear Regression</h3>
<p>Multiple regression includes <strong>multiple predictors</strong>:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + ... + \epsilon\]</span></p>
<p><strong>Example:</strong> Predict GPA from study hours per day AND college:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiple regression</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>multiple_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(GPA <span class="sc">~</span> Study_Hours_Per_Day <span class="sc">+</span> college, <span class="at">data =</span> student_data)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multiple_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## 
## Call:
## lm(formula = GPA ~ Study_Hours_Per_Day + college, data = student_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.59686 -0.13468 -0.00004  0.13485  0.80535 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           1.982091   0.026106  75.925   &lt;2e-16 ***
## Study_Hours_Per_Day   0.154089   0.003185  48.378   &lt;2e-16 ***
## collegeCommunication -0.015106   0.016245  -0.930   0.3525    
## collegeEducation     -0.016020   0.014551  -1.101   0.2711    
## collegeHumanities    -0.024114   0.014151  -1.704   0.0885 .  
## collegeMedicine      -0.029582   0.014500  -2.040   0.0415 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.2027 on 1994 degrees of freedom
## Multiple R-squared:  0.5405, Adjusted R-squared:  0.5394 
## F-statistic: 469.2 on 5 and 1994 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Interpretation:</strong></p>
<ul>
<li><strong>Intercept (1.98)</strong>: Predicted score for Arts &amp; Sciences college (reference) with 0 study hours</li>
<li><strong>study_hours (0.15)</strong>: Each additional hour increases GPA by 0.15 points, <em>controlling for college</em></li>
<li><strong>collegeCommunication (-0.02)</strong>: Communication students have GPA 0.02 points lower than Arts &amp; Sciences (not significant, p = 0.35)</li>
<li><strong>collegeEducation (-0.02)</strong>: Education students have GPA 0.02 points lower than Arts &amp; Sciences (not significant, p = 0.27)</li>
<li><strong>collegeHumanities (-0.02)</strong>: Humanities students have GPA 0.02 points lower than Arts &amp; Sciences (marginally significant, p = 0.09)</li>
<li><strong>collegeMedicine (-0.03)</strong>: Medicine students have GPA 0.03 points lower than Arts &amp; Sciences (significant, p = 0.04)</li>
</ul>
<p><strong>How to report:</strong> <em>A multiple linear regression was conducted to predict GPA from daily study hours and college. The overall model was significant, F(5, 1994) = 469.2, p &lt; .001, R² = .54, indicating that the predictors explained 54% of the variance in GPA. Study hours was a significant positive predictor of GPA (<span class="math display">\[\beta\]</span> = 0.15, p &lt; .001), such that each additional hour of daily study was associated with a 0.15-point increase in GPA, controlling for college. Among colleges, only Medicine students differed significantly from Arts &amp; Sciences students (<span class="math display">\[\beta\]</span> = -0.03, p = .04), though this difference was negligible in magnitude.</em></p>
<hr>
</section>
<section id="dummy-variables" class="level3">
<h3 class="anchored" data-anchor-id="dummy-variables">2.4 Dummy Variables</h3>
<p><mark>Categorical variables are automatically converted to <strong>dummy variables</strong> (0/1 indicators).</mark></p>
<p>For <code>college</code> with 5 levels (Arts &amp; Sciences, Communication, Education, Humanities and Medicine): - R creates 4 dummy variables (k-1 for k categories) - <strong>Reference category:</strong> Arts &amp; Sciences (alphabetically first, or set manually) - <strong>collegeCommunication</strong> = 1 if Communication, 0 otherwise - <strong>collegeEducation</strong> = 1 if Education, 0 otherwise - <strong>collegeHumanities</strong> = 1 if Humanities, 0 otherwise - <strong>collegeMedicine</strong> = 1 if Medicine, 0 otherwise</p>
<p><strong>Changing the reference category:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make CS the reference category</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>student_data<span class="sc">$</span>college <span class="ot">&lt;-</span> <span class="fu">factor</span>(student_data<span class="sc">$</span>college, </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Communication"</span>, <span class="st">"Arts &amp; Sciences"</span>, <span class="st">"Education"</span>, <span class="st">"Humanities"</span>, <span class="st">"Medicine"</span>))</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Refit model</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>multiple_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(GPA <span class="sc">~</span> Study_Hours_Per_Day <span class="sc">+</span> college, <span class="at">data =</span> student_data)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multiple_model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## 
## Call:
## lm(formula = GPA ~ Study_Hours_Per_Day + college, data = student_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.59686 -0.13468 -0.00004  0.13485  0.80535 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             1.9669847  0.0269263  73.051   &lt;2e-16 ***
## Study_Hours_Per_Day     0.1540891  0.0031851  48.378   &lt;2e-16 ***
## collegeArts &amp; Sciences  0.0151065  0.0162449   0.930    0.353    
## collegeEducation       -0.0009134  0.0155413  -0.059    0.953    
## collegeHumanities      -0.0090078  0.0151666  -0.594    0.553    
## collegeMedicine        -0.0144753  0.0154902  -0.934    0.350    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.2027 on 1994 degrees of freedom
## Multiple R-squared:  0.5405, Adjusted R-squared:  0.5394 
## F-statistic: 469.2 on 5 and 1994 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Interpretation:</strong></p>
<ul>
<li><strong>Intercept (1.97)</strong>: Predicted GPA for Communication students (reference) with 0 study hours</li>
<li><strong>Study_Hours_Per_Day (0.15)</strong>: Each additional hour increases GPA by 0.15 points, <em>controlling for college</em></li>
<li><strong>collegeArts &amp; Sciences (0.02)</strong>: Arts &amp; Sciences students have GPA 0.02 points higher than Communication (not significant, p = .35)</li>
<li><strong>collegeEducation (-0.001)</strong>: Education students have GPA 0.001 points lower than Communication (not significant, p = .95)</li>
<li><strong>collegeHumanities (-0.01)</strong>: Humanities students have GPA 0.01 points lower than Communication (not significant, p = .55)</li>
<li><strong>collegeMedicine (-0.01)</strong>: Medicine students have GPA 0.01 points lower than Communication (not significant, p = .35)</li>
</ul>
<p><strong>How to report:</strong> <em>A multiple linear regression was conducted to predict GPA from daily study hours and college. The overall model was significant, F(5, 1994) = 469.2, p &lt; .001, R² = .54, indicating that the predictors explained 54% of the variance in GPA. Study hours was a significant positive predictor of GPA (β = 0.15, p &lt; .001), such that each additional hour of daily study was associated with a 0.15-point increase in GPA, controlling for college. No significant differences in GPA were found between colleges (all p &gt; .05).</em></p>
<p><strong>Note:</strong> In this model, Communication is the reference category (now alphabetically first after releveling). Compare these results to the previous model where Arts &amp; Sciences was the reference:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 41%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>College</th>
<th>vs.&nbsp;Arts &amp; Sciences (previous)</th>
<th>vs.&nbsp;Communication (current)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Arts &amp; Sciences</td>
<td>— (reference)</td>
<td>+0.02 (p = .35)</td>
</tr>
<tr class="even">
<td>Communication</td>
<td>-0.02 (p = .35)</td>
<td>— (reference)</td>
</tr>
<tr class="odd">
<td>Education</td>
<td>-0.02 (p = .27)</td>
<td>-0.001 (p = .95)</td>
</tr>
<tr class="even">
<td>Humanities</td>
<td>-0.02 (p = .09)</td>
<td>-0.01 (p = .55)</td>
</tr>
<tr class="odd">
<td>Medicine</td>
<td>-0.03 (p = .04)</td>
<td>-0.01 (p = .35)</td>
</tr>
</tbody>
</table>
<p>The coefficients change because they now represent differences from Communication instead of Arts &amp; Sciences. However, the overall model fit (R², F-statistic) and the effect of Study_Hours_Per_Day remain identical. Changing the reference category only changes <em>how</em> we interpret the college differences, not the underlying relationships in the data.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reset to alphabetical order</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Reset to alphabetical order</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>student_data<span class="sc">$</span>college <span class="ot">&lt;-</span> <span class="fu">as.character</span>(student_data<span class="sc">$</span>college)  <span class="co"># Convert back to character first</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>student_data<span class="sc">$</span>college <span class="ot">&lt;-</span> <span class="fu">factor</span>(student_data<span class="sc">$</span>college)        <span class="co"># Then re-factor (alphabetical by default)</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(student_data<span class="sc">$</span>college)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>##  Factor w/ 5 levels "Arts &amp; Sciences",..: 3 4 1 2 4 3 2 4 4 4 ...</code></pre>
<hr>
</section>
</section>
<section id="visualizing-regression" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-regression">3. Visualizing Regression</h2>
<section id="scatter-plots-with-regression-lines" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plots-with-regression-lines">3.1 Scatter Plots with Regression Lines</h3>
<p><strong>Simple regression:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(student_data, <span class="fu">aes</span>(<span class="at">x =</span> Study_Hours_Per_Day, <span class="at">y =</span> GPA)) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"GPA vs. Study Hours"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"R² ="</span>, <span class="fu">round</span>(<span class="fu">summary</span>(simple_model)<span class="sc">$</span>r.squared, <span class="dv">3</span>)),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Study Hours"</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"GPA"</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-16-1.png" class="img-fluid"><!-- --></p>
<p><strong>By group:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(student_data, <span class="fu">aes</span>(<span class="at">x =</span> Study_Hours_Per_Day, <span class="at">y =</span> GPA, <span class="at">color =</span> college)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"GPA vs. Study Hours by College"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Study Hours"</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"GPA"</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"College"</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>) <span class="sc">+</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-17-1.png" class="img-fluid"><!-- --></p>
<hr>
</section>
<section id="coefficient-plots" class="level3">
<h3 class="anchored" data-anchor-id="coefficient-plots">3.2 Coefficient Plots</h3>
<p>Coefficient plots visualize regression coefficients and their confidence intervals.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get tidy coefficients</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>coef_data <span class="ot">&lt;-</span> <span class="fu">tidy</span>(multiple_model, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>coef_data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## # A tibble: 6 × 7
##   term                 estimate std.error statistic p.value conf.low conf.high
##   &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)            1.98     0.0261     75.9    0        1.93     2.03   
## 2 Study_Hours_Per_Day    0.154    0.00319    48.4    0        0.148    0.160  
## 3 collegeCommunication  -0.0151   0.0162     -0.930  0.353   -0.0470   0.0168 
## 4 collegeEducation      -0.0160   0.0146     -1.10   0.271   -0.0446   0.0125 
## 5 collegeHumanities     -0.0241   0.0142     -1.70   0.0885  -0.0519   0.00364
## 6 collegeMedicine       -0.0296   0.0145     -2.04   0.0415  -0.0580  -0.00114</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove intercept for better visualization</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>coef_plot_data <span class="ot">&lt;-</span> coef_data <span class="sc">|&gt;</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">!=</span> <span class="st">"(Intercept)"</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coef_plot_data, <span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">y =</span> <span class="fu">reorder</span>(term, estimate))) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> conf.low, <span class="at">xmax =</span> conf.high), <span class="at">height =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Regression Coefficients"</span>,</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Error bars show 95% confidence intervals"</span>,</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Coefficient Estimate"</span>,</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predictor"</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-19-1.png" class="img-fluid"><!-- --></p>
<p><strong>Reading the coefficient plot:</strong></p>
<ul>
<li>If the confidence interval <strong>crosses the red dashed line (0)</strong>, the coefficient is <strong>not statistically significant</strong> (p &gt; .05)</li>
<li>If the confidence interval <strong>does not cross 0</strong>, the coefficient is <strong>statistically significant</strong> (p &lt; .05)</li>
<li>Points to the <strong>right of 0</strong> indicate <strong>positive relationships</strong> (as the predictor increases, GPA increases)</li>
<li>Points to the <strong>left of 0</strong> indicate <strong>negative relationships</strong> (as the predictor increases, GPA decreases)</li>
<li>The <strong>further from 0</strong>, the <strong>stronger the effect</strong></li>
</ul>
<p><strong>Why does crossing zero mean not significant?</strong></p>
<p>A coefficient of 0 means “no effect” — the predictor has no relationship with the outcome. The 95% confidence interval represents the range of plausible values for the true coefficient. If this range includes 0, we cannot rule out the possibility that the true effect is zero (i.e., no effect). Therefore, we cannot confidently say the predictor has a real effect, and the result is not statistically significant.</p>
<hr>
</section>
<section id="marginal-effects-plots" class="level3">
<h3 class="anchored" data-anchor-id="marginal-effects-plots">3.3 Marginal Effects Plots</h3>
<p>Marginal effects show how predicted values change across levels of a predictor.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("ggeffects")</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Marginal effects for study_hours</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>effects_hours <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(multiple_model, <span class="at">terms =</span> <span class="st">"Study_Hours_Per_Day"</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(effects_hours) <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Marginal Effect of Study Hours on GPA"</span>,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Study Hours"</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted GPA"</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-20-1.png" class="img-fluid"><!-- --></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Marginal effects for major</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>effects_major <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(multiple_model, <span class="at">terms =</span> <span class="st">"college"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(effects_major) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Predicted GPA by College"</span>,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Controlling for Study Hours"</span>,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Major"</span>,</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted GPA"</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-21-1.png" class="img-fluid"><!-- --></p>
<hr>
<section id="class-exercise-regression" class="level4">
<h4 class="anchored" data-anchor-id="class-exercise-regression">Class Exercise: Regression</h4>
<ol type="1">
<li>Fit a simple regression predicting <code>GPA</code> from <code>Sleep_Hours_Per_Day</code>.</li>
<li>Add <code>Stress_Level</code> as a second predictor. Does it improve the model?</li>
<li>Create a coefficient plot for your multiple regression.</li>
<li>Interpret the coefficients in plain language.</li>
</ol>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Your workspace</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
</section>
</section>
<section id="generalized-linear-models-glms" class="level2">
<h2 class="anchored" data-anchor-id="generalized-linear-models-glms">4. Generalized Linear Models (GLMs)</h2>
<section id="when-to-use-glms" class="level3">
<h3 class="anchored" data-anchor-id="when-to-use-glms">4.1 When to Use GLMs</h3>
<p>Linear regression assumes the outcome is <strong>continuous and normally distributed</strong>. GLMs (Generalized Linear Models) extend regression to other types of outcomes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Outcome Type</th>
<th>Distribution</th>
<th>Link Function</th>
<th>R Function</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Continuous</td>
<td>Normal</td>
<td>Identity</td>
<td><code>lm()</code></td>
<td>GPA, income, height</td>
</tr>
<tr class="even">
<td>Binary (0/1)</td>
<td>Binomial</td>
<td>Logit</td>
<td><code>glm(family = binomial)</code></td>
<td>Pass/fail, yes/no</td>
</tr>
<tr class="odd">
<td>Count</td>
<td>Poisson</td>
<td>Log</td>
<td><code>glm(family = poisson)</code></td>
<td>Number of events, frequency</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="poisson-regression" class="level3">
<h3 class="anchored" data-anchor-id="poisson-regression">4.2 Poisson Regression</h3>
<p>For <strong>count data</strong> (e.g., number of books read):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Poisson regression</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>poisson_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(books_read <span class="sc">~</span> Study_Hours_Per_Day, </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">family =</span> poisson, </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> student_data)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(poisson_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## 
## Call:
## glm(formula = books_read ~ Study_Hours_Per_Day, family = poisson, 
##     data = student_data)
## 
## Coefficients:
##                      Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)          1.641480   0.053498   30.68   &lt;2e-16 ***
## Study_Hours_Per_Day -0.004785   0.007039   -0.68    0.497    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 2080.0  on 1999  degrees of freedom
## Residual deviance: 2079.5  on 1998  degrees of freedom
## AIC: 8799.6
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p><strong>Interpretation:</strong></p>
<ul>
<li><strong>Intercept (1.64)</strong>: Log of expected books read when Study_Hours_Per_Day = 0</li>
<li><strong>Study_Hours_Per_Day (-0.005)</strong>: Each additional study hour decreases log(books) by 0.005 (not significant, p = .497)</li>
</ul>
<p><strong>To interpret on original scale, exponentiate:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Incident Rate Ratio</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(poisson_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>##         (Intercept) Study_Hours_Per_Day 
##           5.1628048           0.9952264</code></pre>
<ul>
<li><strong>Intercept</strong>: exp(1.64) = 5.16 — Students who study 0 hours are expected to read about 5 books</li>
<li><strong>Study_Hours_Per_Day</strong>: exp(-0.005) = 0.995 — Each additional study hour multiplies expected books read by 0.995 (a 0.5% decrease), but this is not significant</li>
</ul>
<p><strong>Conclusion:</strong> Study hours is <strong>not a significant predictor</strong> of books read (p = .497). The incident rate ratio of 0.995 is very close to 1, indicating essentially no relationship between study hours and number of books read.</p>
<p><strong>Visualize:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create predictions</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>pred_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Study_Hours_Per_Day =</span> <span class="fu">seq</span>(<span class="fu">min</span>(student_data<span class="sc">$</span>Study_Hours_Per_Day), </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">max</span>(student_data<span class="sc">$</span>Study_Hours_Per_Day), </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>pred_data<span class="sc">$</span>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(poisson_model, <span class="at">newdata =</span> pred_data, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(student_data, <span class="fu">aes</span>(<span class="at">x =</span> Study_Hours_Per_Day, <span class="at">y =</span> books_read)) <span class="sc">+</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> pred_data, <span class="fu">aes</span>(<span class="at">y =</span> predicted), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Poisson Regression: Books Read vs. Study Hours"</span>,</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Study Hours"</span>,</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Books"</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-25-1.png" class="img-fluid"><!-- --></p>
<hr>
</section>
</section>
<section id="interaction-terms" class="level2">
<h2 class="anchored" data-anchor-id="interaction-terms">5. Interaction Terms</h2>
<section id="what-are-interactions" class="level3">
<h3 class="anchored" data-anchor-id="what-are-interactions">5.1 What are Interactions?</h3>
<p>An <strong>interaction</strong> occurs when the effect of one predictor <strong>depends on the level</strong> of another predictor.</p>
<p><strong>Example:</strong> Does the effect of study hours on GPA differ by Stress Level?</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model with interaction</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>interaction_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(GPA <span class="sc">~</span> Study_Hours_Per_Day <span class="sc">*</span> Stress_Level, <span class="at">data =</span> student_data)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(interaction_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## 
## Call:
## lm(formula = GPA ~ Study_Hours_Per_Day * Stress_Level, data = student_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.6142 -0.1346 -0.0006  0.1351  0.7902 
## 
## Coefficients:
##                                           Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                               1.988037   0.043275  45.940   &lt;2e-16
## Study_Hours_Per_Day                       0.151930   0.005106  29.757   &lt;2e-16
## Stress_LevelLow                          -0.019358   0.234885  -0.082    0.934
## Stress_LevelModerate                     -0.002176   0.101189  -0.022    0.983
## Study_Hours_Per_Day:Stress_LevelLow       0.003007   0.042425   0.071    0.943
## Study_Hours_Per_Day:Stress_LevelModerate -0.002857   0.014037  -0.204    0.839
##                                             
## (Intercept)                              ***
## Study_Hours_Per_Day                      ***
## Stress_LevelLow                             
## Stress_LevelModerate                        
## Study_Hours_Per_Day:Stress_LevelLow         
## Study_Hours_Per_Day:Stress_LevelModerate    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.2027 on 1994 degrees of freedom
## Multiple R-squared:  0.5405, Adjusted R-squared:  0.5394 
## F-statistic: 469.1 on 5 and 1994 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Interpretation:</strong></p>
<ul>
<li><strong>Intercept (1.99)</strong>: Predicted GPA for High stress students (reference) with 0 study hours</li>
<li><strong>Study_Hours_Per_Day (0.15)</strong>: Effect of study hours on GPA for High stress students — each additional hour increases GPA by 0.15 points</li>
<li><strong>Stress_LevelLow (-0.02)</strong>: Difference in intercept for Low vs.&nbsp;High stress when study hours = 0 (not significant, p = .93)</li>
<li><strong>Stress_LevelModerate (-0.002)</strong>: Difference in intercept for Moderate vs.&nbsp;High stress when study hours = 0 (not significant, p = .98)</li>
<li><strong>Study_Hours_Per_Day:Stress_LevelLow (0.003)</strong>: How much the slope differs for Low vs.&nbsp;High stress students (not significant, p = .94)</li>
<li><strong>Study_Hours_Per_Day:Stress_LevelModerate (-0.003)</strong>: How much the slope differs for Moderate vs.&nbsp;High stress students (not significant, p = .84)</li>
</ul>
<p><strong>Conclusion:</strong> The interaction terms are <strong>not significant</strong> (all p &gt; .05), indicating that the effect of study hours on GPA <strong>does not differ</strong> across stress levels. The relationship between study hours and GPA is consistent regardless of whether students have low, moderate, or high stress.</p>
<p><strong>How to report:</strong> <em>A multiple linear regression with interaction terms was conducted to examine whether the effect of daily study hours on GPA differed by stress level. The overall model was significant, F(5, 1994) = 469.1, p &lt; .001, R² = .54. Study hours was a significant positive predictor of GPA (β = 0.15, p &lt; .001). However, the interaction terms between study hours and stress level were not significant (all p &gt; .83), indicating that the effect of study hours on GPA did not vary by stress level.</em></p>
<hr>
</section>
<section id="visualizing-interactions" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-interactions">5.2 Visualizing Interactions</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Marginal effects with interaction</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>effects_interaction <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(interaction_model, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"Study_Hours_Per_Day"</span>, <span class="st">"Stress_Level"</span>))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(effects_interaction) <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Interaction: Study Hours × Stress Level"</span>,</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Study Hours"</span>,</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted GPA"</span>,</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Stress Level"</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-27-1.png" class="img-fluid"><!-- --></p>
<p><strong>Visual Interpretation of the Interaction Plot</strong></p>
<p>Looking at the interaction plot:</p>
<ul>
<li><strong>X-axis (Study Hours):</strong> Ranges from 5 to 10 hours</li>
<li><strong>Y-axis (Predicted GPA):</strong> Shows the expected GPA values</li>
<li><strong>Three lines:</strong> Representing the three stress levels (Moderate, Low, High)</li>
</ul>
<p><strong>Key Observations:</strong></p>
<ol type="1">
<li><strong>Nearly Parallel Lines:</strong>
<ul>
<li>All three lines (Moderate, Low, and High stress) follow almost the same trajectory as study hours increase</li>
<li>They maintain roughly the same distance from each other throughout the range of study hours</li>
<li>This suggests that the effect of study hours on GPA is consistent across different stress levels</li>
</ul></li>
<li><strong>Positive Slopes:</strong>
<ul>
<li>All lines show an upward trend, confirming that more study hours predict higher GPA regardless of stress level</li>
<li>The slopes appear very similar across all three stress levels</li>
</ul></li>
<li><strong>Minimal Divergence:</strong>
<ul>
<li>The lines stay roughly equidistant from each other</li>
<li>There is no meaningful crossing or substantial convergence/divergence</li>
<li>The confidence intervals (shaded regions) overlap considerably</li>
</ul></li>
</ol>
<p><strong>Interpretation:</strong></p>
<p><strong>No Meaningful Interaction Effect</strong></p>
<p>The parallel nature of these lines indicates that: - Study hours affect GPA in the same way regardless of whether a student experiences low, moderate, or high stress - A student who studies an additional hour can expect roughly the same GPA increase whether they are highly stressed or not stressed - Stress level does not modify the relationship between study hours and GPA</p>
<hr>
<p><strong>General Note on Interpreting Interaction Plots</strong></p>
<p><strong>Understanding Line Patterns:</strong></p>
<p><strong>Parallel Lines = No Interaction</strong> When lines are parallel: - The effect of the predictor (e.g., study hours) is <strong>consistent</strong> across all levels of the moderator (e.g., stress level) - One variable does not change how the other variable affects the outcome - Example: If studying 1 more hour increases GPA by 0.2 points for low-stress students, it also increases GPA by approximately 0.2 points for high-stress students</p>
<p><strong>Diverging or Converging Lines = Interaction Present</strong> When lines diverge (spread apart) or converge (come together): - The effect of the predictor <strong>depends on</strong> the level of the moderator - The relationship between variables changes based on the context - Example: Studying might help low-stress students a lot (steep slope) but help high-stress students less (flatter slope)</p>
<p><strong>Crossing Lines = Strong Interaction</strong> When lines cross: - The direction of the effect can <strong>reverse</strong> depending on the moderator level - This is a particularly strong form of interaction - Example: At low study hours, stressed students might perform better, but at high study hours, non-stressed students might excel</p>
<p><strong>What to Look For:</strong> 1. <strong>Slope differences:</strong> Do the lines have different angles? 2. <strong>Spacing changes:</strong> Do the lines get closer or farther apart? 3. <strong>Crossings:</strong> Do any lines intersect? 4. <strong>Confidence intervals:</strong> Do the shaded regions overlap? (Wide overlap suggests uncertainty about whether lines truly differ)</p>
<p>In our case, the lines are nearly parallel with overlapping confidence intervals, strongly suggesting <strong>no interaction effect</strong> between study hours and stress level on GPA.</p>
<hr>
</section>
</section>
<section id="model-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="model-diagnostics">6. Model Diagnostics</h2>
<section id="assumptions-of-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="assumptions-of-linear-regression">6.1 Assumptions of Linear Regression</h3>
<p>Linear regression assumes:</p>
<ol type="1">
<li><strong>Linearity</strong>: Relationship between X and Y is linear</li>
<li><strong>Independence</strong>: Observations are independent</li>
<li><strong>Homoscedasticity</strong>: Constant variance of residuals</li>
<li><strong>Normality</strong>: Residuals are normally distributed</li>
</ol>
<hr>
</section>
<section id="checking-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="checking-assumptions">6.2 Checking Assumptions</h3>
<p><strong>Built-in diagnostic plots:</strong></p>
<p><strong>Interpreting the Diagnostic Plots:</strong></p>
<ol type="1">
<li><strong>Residuals vs Fitted</strong> (Top Left):
<ul>
<li>Should show no clear pattern</li>
<li>Points should be randomly scattered around the horizontal line at 0</li>
<li>A pattern suggests non-linearity or heteroscedasticity</li>
</ul></li>
<li><strong>Q-Q Plot</strong> (Top Right):
<ul>
<li>Points should fall along the diagonal line</li>
<li>Deviations suggest residuals are not normally distributed</li>
<li>Particularly concerning if points curve away at the ends</li>
</ul></li>
<li><strong>Scale-Location</strong> (Bottom Left):
<ul>
<li>Should show a horizontal line with randomly scattered points</li>
<li>Tests for homoscedasticity (constant variance)</li>
<li>An upward or downward trend suggests heteroscedasticity</li>
</ul></li>
<li><strong>Residuals vs Leverage</strong> (Bottom Right):
<ul>
<li>Identifies influential observations</li>
<li>Points outside Cook’s distance lines (dashed lines) are influential</li>
<li>These points have a large impact on the regression coefficients</li>
</ul></li>
</ol>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Four diagnostic plots</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(simple_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-28-1.png" class="img-fluid"><!-- --></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Interpreting Our Diagnostic Plots:</strong></p>
<p>Looking at our model’s diagnostic plots:</p>
<ol type="1">
<li><strong>Residuals vs Fitted</strong> (Top Left):
<ul>
<li>Points are randomly scattered around the horizontal line at 0</li>
<li>No clear pattern or curvature is visible</li>
<li>The red line is approximately horizontal</li>
<li><strong>Conclusion:</strong> Linearity assumption is satisfied ✓</li>
</ul></li>
<li><strong>Q-Q Plot</strong> (Top Right):
<ul>
<li>Points fall closely along the diagonal reference line</li>
<li>Minor deviations at the extreme ends (points 702, 118, 485)</li>
<li>Most points align well with the theoretical quantiles</li>
<li><strong>Conclusion:</strong> Normality assumption is largely satisfied ✓</li>
</ul></li>
<li><strong>Scale-Location</strong> (Bottom Left):
<ul>
<li>Points are evenly distributed across fitted values</li>
<li>The red line is relatively flat with slight variation</li>
<li>No obvious funnel or cone shape</li>
<li><strong>Conclusion:</strong> Homoscedasticity assumption is satisfied ✓</li>
</ul></li>
<li><strong>Residuals vs Leverage</strong> (Bottom Right):
<ul>
<li>Most points cluster near low leverage values</li>
<li>A few points (702, 480, 52) have higher leverage</li>
<li>No points fall outside Cook’s distance lines (not visible on plot)</li>
<li><strong>Conclusion:</strong> No highly influential outliers detected ✓</li>
</ul></li>
</ol>
<p><strong>Overall Assessment:</strong></p>
<p>Our interaction model meets all key assumptions of linear regression: - The relationship is linear - Residuals show constant variance - Residuals are approximately normally distributed - No problematic influential points</p>
<p>The model is reliable and the statistical inferences (p-values, confidence intervals) are valid.</p>
<hr>
</section>
<section id="the-performance-package" class="level3">
<h3 class="anchored" data-anchor-id="the-performance-package">6.3 The performance Package</h3>
<p>The <code>performance</code> package provides easy model diagnostics:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("performance")</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check all assumptions</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(simple_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-29-1.png" class="img-fluid"><!-- --></p>
<p>Alternatively, use the <code>performance</code> package for comprehensive diagnostics:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(interaction_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="bigdata_L6-github_files/figure-gfm/unnamed-chunk-30-1.png" class="img-fluid"><!-- --></p>
<p><strong>Interpreting the Posterior Predictive Check:</strong></p>
<p>This plot compares the distribution of observed data (green line) with simulated data from the model (blue lines):</p>
<ul>
<li><strong>Green line:</strong> The actual distribution of GPA values in our dataset</li>
<li><strong>Blue lines:</strong> Multiple simulated datasets generated from our fitted model</li>
<li><strong>What to look for:</strong> The blue lines should closely match the green line</li>
</ul>
<p><strong>In our case:</strong></p>
<ul>
<li>The model-predicted distributions (blue) closely overlap with the observed data (green)</li>
<li>Both show a bell-shaped, approximately normal distribution centered around 3.0</li>
<li>The peak, spread, and shape are well-matched</li>
<li>No systematic deviations or mismatches are visible</li>
<li><strong>Conclusion:</strong> The model accurately captures the distribution of GPA values ✓</li>
</ul>
<p>This provides additional evidence that our model is well-specified and that the assumptions are met. The model not only fits individual data points well (as shown in the diagnostic plots) but also reproduces the overall distribution of the outcome variable.</p>
<hr>
<p><strong>Individual checks:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normality of residuals</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(simple_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## OK: residuals appear as normally distributed (p = 0.403).</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Homoscedasticity</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(simple_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## OK: Error variance appears to be homoscedastic (p = 0.917).</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multicollinearity (for multiple regression)</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">check_collinearity</span>(multiple_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## # Check for Multicollinearity
## 
## Low Correlation
## 
##                 Term  VIF  VIF 95% CI adj. VIF Tolerance Tolerance 95% CI
##  Study_Hours_Per_Day 1.00 [1.00, Inf]     1.00      1.00     [0.00, 1.00]
##              college 1.00 [1.00, Inf]     1.00      1.00     [0.00, 1.00]</code></pre>
<p><strong>Performance Package Output:</strong></p>
<p>The <code>check_model()</code> function provides a comprehensive summary of model diagnostics:</p>
<p><strong>Normality of Residuals:</strong> - Test result: OK (p = 0.403) - p-value &gt; 0.05 indicates we fail to reject the null hypothesis of normality - <strong>Conclusion:</strong> Residuals are normally distributed ✓</p>
<p><strong>Homoscedasticity (Constant Variance):</strong> - Test result: OK (p = 0.917) - p-value &gt; 0.05 indicates we fail to reject the null hypothesis of homoscedasticity - <strong>Conclusion:</strong> Error variance is constant across fitted values ✓</p>
<p><strong>Multicollinearity Check:</strong></p>
<p>Multicollinearity occurs when predictor variables are highly correlated with each other, which can make coefficient estimates unstable.</p>
<p><strong>VIF (Variance Inflation Factor) Interpretation:</strong> - VIF = 1: No correlation with other predictors - VIF &lt; 5: Low multicollinearity (acceptable) - VIF 5-10: Moderate multicollinearity (concerning) - VIF &gt; 10: High multicollinearity (problematic)</p>
<p><strong>In our model:</strong> - <code>Study_Hours_Per_Day</code>: VIF = 1.00 - <code>college</code>: VIF = 1.00 - Both predictors have VIF = 1.00, indicating <strong>no multicollinearity</strong> - Tolerance values = 1.00 (inverse of VIF) confirm this - <strong>Conclusion:</strong> Predictors are independent; coefficient estimates are stable ✓</p>
<p><strong>Overall Model Assessment:</strong></p>
<p>All diagnostic checks passed: ✓ Linearity assumption met<br>
✓ Normality of residuals confirmed<br>
✓ Homoscedasticity confirmed<br>
✓ No multicollinearity detected<br>
✓ No influential outliers</p>
<p>The model is statistically sound and reliable for inference.</p>
<hr>
<p><strong>Compare models:</strong></p>
<p>After fitting multiple models, we can compare their performance to determine which best explains the data.</p>
<p><strong>Models to Compare:</strong></p>
<ol type="1">
<li><strong>Simple Model:</strong> <code>GPA ~ Study_Hours_Per_Day</code></li>
<li><strong>Multiple Model:</strong> <code>GPA ~ Study_Hours_Per_Day + college</code></li>
</ol>
<p>Use the <code>compare_performance()</code> function from the <code>performance</code> package:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">compare_performance</span>(simple_model, multiple_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>## # Comparison of Model Performance Indices
## 
## Name           | Model |  AIC (weights) | AICc (weights) |  BIC (weights)
## -------------------------------------------------------------------------
## simple_model   |    lm | -703.5 (0.835) | -703.5 (0.838) | -686.7 (&gt;.999)
## multiple_model |    lm | -700.3 (0.165) | -700.2 (0.162) | -661.1 (&lt;.001)
## 
## Name           |    R2 | R2 (adj.) |  RMSE | Sigma
## --------------------------------------------------
## simple_model   | 0.539 |     0.539 | 0.203 | 0.203
## multiple_model | 0.541 |     0.539 | 0.202 | 0.203</code></pre>
<p><strong>Understanding the Output:</strong></p>
<p>The comparison table provides several metrics to evaluate model fit:</p>
<p><strong>Information Criteria (Lower is Better):</strong></p>
<ul>
<li><strong>AIC (Akaike Information Criterion):</strong> Balances model fit and complexity
<ul>
<li>Simple model: -703.5 (weight = 0.835)</li>
<li>Multiple model: -700.3 (weight = 0.165)</li>
<li><strong>Lower AIC indicates better fit; simple model is preferred</strong></li>
</ul></li>
<li><strong>AICc (Corrected AIC):</strong> Adjusted for small sample sizes
<ul>
<li>Simple model: -703.5 (weight = 0.838)</li>
<li>Multiple model: -700.2 (weight = 0.162)</li>
<li><strong>Results align with AIC</strong></li>
</ul></li>
<li><strong>BIC (Bayesian Information Criterion):</strong> More strongly penalizes complexity
<ul>
<li>Simple model: -686.7 (weight &gt; .999)</li>
<li>Multiple model: -661.1 (weight &lt; .001)</li>
<li><strong>Strongly favors the simpler model</strong></li>
</ul></li>
</ul>
<p><strong>Model Fit Metrics:</strong></p>
<ul>
<li><strong>R² (R-squared):</strong>
<ul>
<li>Simple model: 0.539</li>
<li>Multiple model: 0.541</li>
<li><strong>Nearly identical; adding college explains only 0.2% more variance</strong></li>
</ul></li>
<li><strong>Adjusted R²:</strong> Accounts for number of predictors
<ul>
<li>Both models: 0.539</li>
<li><strong>No improvement when adjusting for additional predictors</strong></li>
</ul></li>
<li><strong>RMSE (Root Mean Square Error):</strong> Average prediction error
<ul>
<li>Simple model: 0.203</li>
<li>Multiple model: 0.202</li>
<li><strong>Essentially identical prediction accuracy</strong></li>
</ul></li>
<li><strong>Sigma:</strong> Residual standard error
<ul>
<li>Both models: 0.203</li>
<li><strong>No difference in error variance</strong></li>
</ul></li>
</ul>
<p><strong>Interpretation:</strong></p>
<p><strong>The simple model (GPA ~ Study_Hours_Per_Day) is preferred because:</strong> - Lower AIC and BIC indicate better balance of fit and parsimony - Adding <code>college</code> as a predictor provides negligible improvement in R² - Prediction accuracy (RMSE) is virtually unchanged - The principle of parsimony suggests choosing the simpler model when performance is equivalent</p>
<p><strong>Conclusion:</strong> Study hours alone adequately predict GPA; college affiliation does not meaningfully improve the model.</p>
<hr>
</section>
</section>
<section id="class-exercise" class="level2">
<h2 class="anchored" data-anchor-id="class-exercise">Class Exercise</h2>
<p>Using the <code>mtcars</code> dataset:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mtcars)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
<ol type="1">
<li><p><strong>T-test:</strong> Compare <code>mpg</code> between automatic (am=0) and manual (am=1) transmissions.</p></li>
<li><p><strong>ANOVA:</strong> Compare <code>mpg</code> across different numbers of cylinders (<code>cyl</code>).</p></li>
<li><p><strong>Simple Regression:</strong> Predict <code>mpg</code> from <code>wt</code> (weight). Interpret the coefficients.</p></li>
<li><p><strong>Multiple Regression:</strong> Add <code>hp</code> (horsepower) to your model. Does it improve fit?</p></li>
<li><p><strong>Coefficient Plot:</strong> Create a coefficient plot for your multiple regression.</p></li>
<li><p><strong>Diagnostics:</strong> Check the assumptions of your final model.</p></li>
<li><p><strong>Report:</strong> Write a brief summary of your findings as you would for an academic paper.</p></li>
</ol>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Your workspace</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
<section id="lecture-6-cheat-sheet" class="level2">
<h2 class="anchored" data-anchor-id="lecture-6-cheat-sheet">Lecture 6 Cheat Sheet</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Function/Concept</strong></th>
<th><strong>Description</strong></th>
<th><strong>Code Example</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>t.test()</code></td>
<td>Compare means of two groups</td>
<td><code>t.test(y ~ group, data = df)</code></td>
</tr>
<tr class="even">
<td><code>aov()</code></td>
<td>One-way ANOVA</td>
<td><code>aov(y ~ group, data = df)</code></td>
</tr>
<tr class="odd">
<td><code>TukeyHSD()</code></td>
<td>Post-hoc test after ANOVA</td>
<td><code>TukeyHSD(aov_result)</code></td>
</tr>
<tr class="even">
<td><code>lm()</code></td>
<td>Linear regression</td>
<td><code>lm(y ~ x1 + x2, data = df)</code></td>
</tr>
<tr class="odd">
<td><code>glm()</code></td>
<td>Generalized linear model</td>
<td><code>glm(y ~ x, family = poisson)</code></td>
</tr>
<tr class="even">
<td><code>summary()</code></td>
<td>Model summary</td>
<td><code>summary(model)</code></td>
</tr>
<tr class="odd">
<td><code>coef()</code></td>
<td>Extract coefficients</td>
<td><code>coef(model)</code></td>
</tr>
<tr class="even">
<td><code>predict()</code></td>
<td>Generate predictions</td>
<td><code>predict(model, newdata)</code></td>
</tr>
<tr class="odd">
<td><code>broom::tidy()</code></td>
<td>Tidy model output</td>
<td><code>tidy(model, conf.int = TRUE)</code></td>
</tr>
<tr class="even">
<td><code>broom::glance()</code></td>
<td>Model fit statistics</td>
<td><code>glance(model)</code></td>
</tr>
<tr class="odd">
<td><code>geom_smooth(method="lm")</code></td>
<td>Add regression line</td>
<td><code>geom_smooth(method = "lm")</code></td>
</tr>
<tr class="even">
<td><code>ggeffects::ggpredict()</code></td>
<td>Marginal effects</td>
<td><code>ggpredict(model, terms = "x")</code></td>
</tr>
<tr class="odd">
<td>Interaction term</td>
<td>Effect depends on another variable</td>
<td><code>lm(y ~ x1 * x2)</code></td>
</tr>
<tr class="even">
<td><code>plot(model)</code></td>
<td>Diagnostic plots</td>
<td><code>plot(lm_model)</code></td>
</tr>
<tr class="odd">
<td><code>performance::check_model()</code></td>
<td>Check assumptions</td>
<td><code>check_model(model)</code></td>
</tr>
<tr class="even">
<td><code>compare_performance()</code></td>
<td>Compare models</td>
<td><code>compare_performance(m1, m2)</code></td>
</tr>
<tr class="odd">
<td>R²</td>
<td>Variance explained</td>
<td><code>summary(model)$r.squared</code></td>
</tr>
<tr class="even">
<td>p-value</td>
<td>Statistical significance</td>
<td><code>&lt; 0.05</code> = significant</td>
</tr>
<tr class="odd">
<td>Confidence interval</td>
<td>Range of plausible values</td>
<td>95% CI excludes 0 = significant</td>
</tr>
</tbody>
</table>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Ayse D. Lokmanoglu, Boston University</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:alokman@bu.edu">
      <i class="bi bi-envelope" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/aysedeniz09">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>